# Generated by Django 4.2.2 on 2023-11-24 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloneApp', '0002_alter_comment_create_date_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 9, 54, 16, 514967, tzinfo=datetime.timezone.utc)),
        ),
    ]
